[package]
name = "ez_app"
description = "EZ2DEMOSCENE editor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "ez2demoscene"
path = "src/main.rs"

[dependencies]
ez_core.workspace = true
ez_render.workspace = true
ez_export.workspace = true
wgpu.workspace = true
eframe.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-snarl.workspace = true
image.workspace = true
rfd.workspace = true
rodio = { workspace = true, features = ["playback", "symphonia-all"] }
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
