[package]
name = "ez_render"
description = "wgpu renderer for EZ2DEMOSCENE"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ez_core.workspace = true
wgpu.workspace = true
glam.workspace = true
bytemuck.workspace = true
image.workspace = true
gltf.workspace = true
tobj.workspace = true
anyhow.workspace = true
log.workspace = true
pollster.workspace = true
